### ISSUE TITLE
How to update binded servers after plugin is installed

### ISSUE THREAD

**Issue by davidkhala** [hjdr4/docker-volume-glusterfs#2]
After I installed the docker plugin
`docker plugin install hjdr4plugins/docker-volume-glusterfs args="-servers=srv1:srv2 [-parameter=value]"`
how could we update the servers list without reinstalling the plugin?

**Comment by hjdr4** [comment]
https://docs.docker.com/engine/reference/commandline/plugin_set/#change-the-source-of-the-arguments

**Comment by hjdr4** [comment]
I've been thinking about defining the servers per volume, and I think having more than 1 cluster for one host is not common. Gluster is scalable so having more than one cluster per env is not likely. Having different Gluster env generally means having other Docker hosts for this env. 
Also, the complete list of servers is not necessary. Those nodes are just the bootstrap nodes.

**Comment by davidkhala** [comment]
Actually I am a laymen to glusterFS. And I wonder..
Does gluster support building up based on existing mount point? like a 'gluster layer' on exising NFS?
Or will gluster automatically allocate a path as shared file path?

**Comment by hjdr4** [comment]
I'm not sure I understand the questions. They really are about what GlusterFS is/can do. I suggest you read about official documentation. But I can try to explain a simple case. Docker will be out of scope for now. 

With Gluster, you can setup storage servers (bricks) that will hold parts of volumes. Bricks are just a directory on a server served by Gluster brick server. For example, you can have a stripped volume that will span bricks, just like RAID0. Because it's client/server, you will be able to mount the volume on different clients. So a volume is just something you mount somewhere, just like a NFS share.  
Technically, I think you can have bricks work on top of NFS. But this is non-sense. Gluster is designed to serve bricks data from directly attached storage. Then you can mount volumes on clients, and clients may share the volume using NFS or CIFS.
http://www.admin-magazine.com/var/ezflow_site/storage/images/media/images/f01-glusterfs/48050-1-eng-US/F01-glusterfs_large.jpg

Now about Docker case, using this plugin enables cases similar to NFS plugin (https://github.com/ContainX/docker-volume-netshare for instance). Your containers may serve the same data (images for a web site for instance), or you can have singletons that always have access to the data even when the container is scheduled on other hosts. But unlike NFS, Gluster has built-in replication, geo-replication, dispersed storage, stripping and other interesting properties you really like to have when you work with clusters and high availability.

**Comment by hjdr4** [comment]
The conversation is dead for now. Feel free to comment if you still need support.
